[package]
name = "DoomR"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = {version = "0.4.13", features = ["audio"]}
once_cell = "1.19.0"  
rand = "0.8.4"
[profile.release]
lto = true
codegen-units = 1
panic = "abort"